config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  health_check_routes

  root "rooms#index"

  resources :rooms, only: %i[index show]
  namespace :my do
    resources :rooms, only: %i[index show edit new create update destroy] do
      member do
        delete :remove_image
      end
    end

    resources :reservations, only: %i[index create destroy]do
      member do
        put :confirmed
      end
    end
  end
end

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if success.present? %>
  <div role="alert" class="alert alert-success fade show">
    <%= success %>
  </div>
<% end %>

<% ([error.presence] || [alert.presence]).flatten.each do |message| %>
  <% if message %>
    <div role="alert" class="alert alert-warning alert-dismissible fade show">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

<% if notice.present? %>
  <div role="alert" class="alert alert-info alert-dismissible fade show">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">MtBnb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <%= form_with url: rooms_path, method: :get, data: {turbo_frame: "rooms", turbo_action: "advance"}, class: "d-flex gap-2" do |form| %>
        <div class="form-label">
          <%= form.label :location, "Where" %>
          <%= form.text_field :location, class: "form-control me-2", placeholder: "Search destinations", aria: { label: "Search destinations" } %>
        </div>

        <div class="form-label">
          <%= form.label :start_date, "Start Date" %>
          <%= form.date_field :start_date, class: "form-control me-2", aria: { label: "Start Date" } %>
        </div>

        <div class="form-label">
          <%= form.label :end_date, "End Date" %>
          <%= form.date_field :end_date, class: "form-control me-2", aria: { label: "End Date" } %>
        </div>

        <%= form.submit "Search", class: "btn btn-primary" %>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
              <span><%= current_user.email %></span>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li>
                <%= link_to 'My rooms', my_rooms_path, class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to 'My reservations', my_reservations_path, class: 'dropdown-item' %>
              </li>
              <li class="border-top">
                <%= button_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>
                  Sign out
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_rooms.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @rooms.each do |room| %>
        <div class="col">
          <%= link_to(user_rooms ? my_room_path(room) : room_path(room), class: 'text-decoration-none link-dark') do %>
            <div class="card shadow-sm">
              <div class="p-3">
                <% if room.images.exists? %>
                  <%= image_tag(room.images.first, width: '100%', height: 200) %>
                <% else %>
                  <%= image_tag('no_image', width: '100%', height: 200) %>
                <% end %>
              </div>
              <div class="card-body">
                <p class="card-text"><%= room.name %></p>
                <span><%= room.location %></span>
                <p class="card-text">Price per night: <%= room.price_per_night %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>