config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  health_check_routes

  root "rooms#index"

  resources :rooms, only: %i[index show]
  namespace :my do
    resources :rooms, only: %i[index show edit new create update destroy] do
      member do
        delete :remove_image
      end
    end

    resources :reservations, only: %i[index create destroy]do
      member do
        put :confirmed
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord

  has_one_attached :image
  has_many_attached :gallery_images
  has_rich_text :description

  belongs_to :user
  has_many :reservations, dependent: :destroy

  validates :name, :location, presence: true
  validates :capacity, presence: true, numericality: { greater_than: 0 }
  validates :price_per_night_cents, presence: true, numericality: { greater_than: 0 }

  scope :not_reserved, lambda { |start_date, end_date|
                         where.not(id: Reservation.reserved(start_date, end_date).select(:room_id))
                       }
  scope :by_location, ->(location) { where(location:) }

  def reserved?(start_date, end_date)
    !id.in?(Reservation.reserved(start_date, end_date).pluck(:room_id))
  end

end

app/controllers/my/rooms_controller.rb
class My::RoomsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @rooms = current_user.rooms
  end

  def show
    @reservations = @room.reservations
    render turbo_stream: turbo_stream.replace(
      'room_reservations',
      partial: 'my/rooms/reservations',
      locals:  { room: @room, reservations: @reservations }
    )
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = current_user.rooms.new(rooms_params)
    return render(:new, status: :unprocessable_entity) unless @room.save

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def update
    return render(:edit, status: :unprocessable_entity) unless @room.update(rooms_params)

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def destroy
    @room.destroy

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def remove_image
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge_later
    redirect_back(fallback_location: request.referer)
  end

  private

  def set_room
    @room = current_user.rooms.find(params[:id])
  end

  def rooms_params
    params.require(:room).permit(:name, :location, :capacity,
                                 :price_per_night_cents, :image, gallery_images: [])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all

    if params[:start_date].present? && params[:end_date].present?
      @rooms = Room.not_reserved(params[:start_date], params[:end_date])
    end
    @rooms = @rooms.by_location(params[:location]) if params[:location].present?

    @pagy, @rooms = pagy(@rooms)
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @reservations = Reservation.reserved_dates_room(@room.id)
  end

end

app/controllers/users/rooms_controller.rb
module Users

  class RoomsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_room, except: %i[index new create]

    def index
      @rooms = Room.where(user: current_user)
    end

    def show
      @new_image = ActiveStorage::Attachment.new
    end

    def new
      @room = Room.new
    end

    def edit
    end

    def create
      @room = Room.new(room_params) { |room| room.user = current_user }

      if @room.save
        redirect_to(my_rooms_path, notice: t('.success'))
      else
        render(:new, status: :unprocessable_entity)
      end
    end

    def update
      if @room.update(room_params)
        redirect_to(my_room_path(@room), notice: t('.success'))
      else
        render(:edit, status: :unprocessable_entity)
      end
    end

    def destroy
      return if @room.user_id != current_user.id

      if @room.destroy
        redirect_to(my_rooms_path, notice: t('.success'))
      else
        redirect_to(my_room_path(@room), alert: t('.failed'))
      end
    end

    private

    def room_params
      params.require(:room).permit(
        :name, :location, :price_per_night, :start_date, :end_date, images: []
      )
    end

    def set_room
      @room = Room.where(user: current_user).find(params[:id])
    end

  end

end

app/views/rooms/_carousel.html.erb
<div id="carousel<%= dom_id room %>" class="carousel slide" ">
  <div class="carousel-inner">
    <% if room.image.attached? %>
      <div class="carousel-item active">
        <%= image_tag room.image, class: "object-fit-cover image-height", id: dom_id(room),  style: "view-transition-name: room_#{dom_id(room)}" %>
      </div>
    <% else %>
      <div class="carousel-item active">
        <%= image_tag 'no_img', class: "object-fit-cover image-height", id: dom_id(room), style: "view-transition-name: room_#{dom_id(room)}" %>
      </div>
    <% end %>
    <% if room.gallery_images.attached? %>
      <% room.gallery_images.each do |image| %>
        <div class="carousel-item">
          <%= image_tag image, class: "object-fit-cover image-height", id: dom_id(room), style: "view-transition-name: #{dom_id(room)}" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carousel<%= dom_id room %>" data-bs-slide="prev" onclick="event.stopPropagation();">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel<%= dom_id room %>" data-bs-slide="next" onclick="event.stopPropagation();">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.hidden_field :user_id, value: current_user&.id %>
      <div class="form-group">
        <%= f.label "Name" %>
        <%= f.text_field :name, :class => "form-control" %>
      </div>

      <%= f.fields_for :address do |address_fields| %>
        <div class="form-group">
          <%= address_fields.label "City" %>
          <%= address_fields.text_field :city, :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= address_fields.label "Street" %>
          <%= address_fields.text_field :street, :class => "form-control" %>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label "Price" %>
        <%= f.text_field :price, :class => "form-control" %>
      </div>

      <div class="mt-2">
        <%= submit_tag "#{@room.new_record? ? "Create" : "Update"} Room", class: "btn btn-primary w-100" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Add images</label>
        <%= f.file_field :images, multiple: true, direct_upload: true, :class => "form-control" %>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div class="col-lg-3 col-md-4 col-sm-6 col-12 mb-4" id="<%= dom_id room %>">
    <div class="card" onclick="Turbo.visit('<%= room_path(room) %>', { action: 'replace', frame: 'room_details' })">
    <div id="carousel<%= dom_id room %>" class="carousel slide">
      <%= render partial: 'carousel', locals: { room: room } %>
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel<%= dom_id room %>" data-bs-slide="prev" onclick="event.stopPropagation();">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel<%= dom_id room %>" data-bs-slide="next" onclick="event.stopPropagation();">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <div class="card-block">
      <h4 class="card-title"><%= room.name %></h4>
      <p class="card-text">Location: <%= room.location %></p>
      <p class="card-text">Capacity: <%= room.capacity %></p>
      <p class="card-text"><%= humanized_money_with_symbol(room.price_per_night_cents) %> per night</p>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="container-fluid">
  <h2>Edit Room</h2>

  <%= render "form" %>
</div>

app/views/rooms/index.html.erb
<h1 class="text-center">ROOMS LIST</h1>

<div class="container my-4">
  <%= turbo_frame_tag "rooms", target: "_top" do %>
    <div class="row">
      <%= render @rooms %>
    </div>

    <div class="mt-4">
      <%== pagy_bootstrap_nav(@pagy, link_extra: "data-turbo-frame='rooms'") %>
    </div>
  <% end %>
</div>

app/views/rooms/my_rooms.html.erb
<div class="container-fluid">
  <% if @rooms.blank? %>
    <div class="row">
      <div class="col-md-12 text-center">
        <p>You have no rooms. <%= link_to "Add room", new_room_path, class: "link-primary" %>
        </p>
      </div>
    </div>
  <% else %>
    <div class="d-flex justify-content-between align-items-end">
      <h2>My Rooms</h2>
      <h6><%= link_to "+ Add room", new_room_path, class: "link-primary" %></h6>
    </div>
    <div class="d-flex">
      <% @rooms.each do |room| %>
        <%= link_to room_path(room) do %>
          <div class="card">
            <%= image_tag(url_for(room.images.first), class: "card-img-top") %>
            <div class="card-actions">
              <%= link_to "Edit", edit_room_path(room), class: "btn btn-primary btn-sm text-white" %>
              <%= button_to "Delete", room_path(room), method: :delete, class: "btn btn-danger btn-sm" %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= room.name %></h5>
              <p class="card-text"><%= room.address.city %>, <%= room.address.street %></p>
              <h6 class="card-subtitle mb-2 text-muted">$<%= room.price %></h6>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="container-fluid">
  <h2>Add Room</h2>

  <%= render "form" %>
</div>

app/views/rooms/show.html.erb
<div class="container turn-view" id="show">
  <%= turbo_frame_tag "room_details", target: "_top" do %>
    <h1 class="display-4 text-center mb-5">Room Details</h1>

    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-6">
            <%= render partial: 'carousel', locals: { room: @room } %>
          </div>
          <div class="col-md-6">
            <div class="card mb-3">
              <div class="card-body">
                <h5 class="card-title"><%= @room.name %></h5>
                <p class="card-text">Location: <%= @room.location %></p>
                <p class="card-text">Price per night: <%= humanized_money_with_symbol(@room.price_per_night_cents) %></p>
                <p class="card-text"><%= @room.description %></p>
              </div>
            </div>
            <div class="card mb-3">
              <% if user_signed_in? && @room.user != current_user %>
                <%= turbo_frame_tag "reservation_form", target: "_top" do %>
                  <%= render partial: "my/reservations/form", locals: { reservation: @reservation, room: @room, reservations: @reservations } %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="text-center mt-3">
          <a href="<%= root_path %>" class="btn btn-primary">Back to Rooms List</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/user_rooms.html.erb
<div class="container">
      <div class="py-5 text-center">
        <h2>Vos logements</h2>Envie de mettre son logement en location?</p>
      </div>
      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Mettez un nouveau logement à louer</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>
          <%= simple_form_for(@room) do |f| %>
            <ul class="list-group mb-3">
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Nom de votre logement</h6>
                  <small><%= f.input :title, required:true, label: false, class: "text-muted"%></small>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Description</h6>
                  <%= f.input :description, label: false, class: "text-muted"%>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Prix</h6>
                  <%= f.input :price, label: false, class: "text-muted"%>
                </div>
                <span class="text-muted">(par nuit)</span>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Adresse</h6>
                  <%= f.input :address, label: false, class: "text-muted"%>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Ville</h6>
                  <%= f.input :city, label: false, class: "text-muted"%>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Pays</h6>
                  <%= f.input :country, as: :string, label: false, class: "text-muted"%>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between">
                <%= f.button :submit, class: "btn btn-primary homebtn2" %>
              </li>
            </ul>
          <% end %>
        </div>
        <div class="col-md-8 order-md-1">
          <% @rooms_as_host.each do |room| %>
            <%= form_for room do |f|%>
              <h4 class="mb-3"><%= room.title %></h4>
              <form class="needs-validation" novalidate="">
                <div class="row">
                  <div class="col-md-6 mb-3">
                    <label for="description">Description</label>
                    <%= f.text_field :description, class: "form-control", disabled: true %>
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="lastName">Prix par nuit(€)</label>
                    <%= f.text_field :price, class: "form-control", disabled: true %>
                  </div>
                </div>
                <div class="mb-3">
                  <label for="username">Contact pour ce logement</label>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">@</span>
                    </div>
                    <%= f.text_field :n, value: room.user.email,class: "form-control", disabled: true %>  
                  </div>
                </div>

                <div class="mb-3">
                  <label for="email">Adresse</label>
                    <%= f.text_field :address, class: "form-control", disabled: true %>  
                </div>

                <div class="mb-3">
                  <label for="address">Ville</label>
                    <%= f.text_field :city, class: "form-control", disabled: true %>  
                </div>

                <div class="mb-3">
                  <label for="address2">Pays</label>
                    <%= f.text_field :country, class: "form-control", disabled: true %>  
                </div>
                <%= link_to "Retirer la chambre", room, class: "btn btn-danger",data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                <hr class="mb-4">
              </form>
            <%end %>
          <% end %>
        </div>
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">© 2017-2018 Company Name</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="#">Privacy</a></li>
          <li class="list-inline-item"><a href="#">Terms</a></li>
          <li class="list-inline-item"><a href="#">Support</a></li>
        </ul>
      </footer>
    </div>