config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  health_check_routes

  root "rooms#index"

  resources :rooms, only: %i[index show]
  namespace :my do
    resources :rooms, only: %i[index show edit new create update destroy] do
      member do
        delete :remove_image
      end
    end

    resources :reservations, only: %i[index create destroy]do
      member do
        put :confirmed
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord

  has_one_attached :image
  has_many_attached :gallery_images
  has_rich_text :description

  belongs_to :user
  has_many :reservations, dependent: :destroy

  validates :name, :location, presence: true
  validates :capacity, presence: true, numericality: { greater_than: 0 }
  validates :price_per_night_cents, presence: true, numericality: { greater_than: 0 }

  scope :not_reserved, lambda { |start_date, end_date|
                         where.not(id: Reservation.reserved(start_date, end_date).select(:room_id))
                       }
  scope :by_location, ->(location) { where(location:) }

  def reserved?(start_date, end_date)
    !id.in?(Reservation.reserved(start_date, end_date).pluck(:room_id))
  end

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy

end

app/controllers/my/rooms_controller.rb
class My::RoomsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @rooms = current_user.rooms
  end

  def show
    @reservations = @room.reservations
    render turbo_stream: turbo_stream.replace(
      'room_reservations',
      partial: 'my/rooms/reservations',
      locals:  { room: @room, reservations: @reservations }
    )
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = current_user.rooms.new(rooms_params)
    return render(:new, status: :unprocessable_entity) unless @room.save

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def update
    return render(:edit, status: :unprocessable_entity) unless @room.update(rooms_params)

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def destroy
    @room.destroy

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def remove_image
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge_later
    redirect_back(fallback_location: request.referer)
  end

  private

  def set_room
    @room = current_user.rooms.find(params[:id])
  end

  def rooms_params
    params.require(:room).permit(:name, :location, :capacity,
                                 :price_per_night_cents, :image, gallery_images: [])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all

    if params[:start_date].present? && params[:end_date].present?
      @rooms = Room.not_reserved(params[:start_date], params[:end_date])
    end
    @rooms = @rooms.by_location(params[:location]) if params[:location].present?

    @pagy, @rooms = pagy(@rooms)
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @reservations = Reservation.reserved_dates_room(@room.id)
  end

end

app/controllers/users/images_controller.rb
module Users

  class ImagesController < ApplicationController

    before_action :authenticate_user!

    def destroy
      room = Room.find(params[:my_room_id])
      return unless room.user_id == current_user.id

      room.images.find_by(id: params[:id])&.purge

      redirect_to(my_room_path(room), notice: t('.success'))
    end

  end

end

app/controllers/users/reservations_controller.rb
module Users

  class ReservationsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_reservation, only: %i[edit update destroy]

    def index
      @reservations = Reservation.where(user: current_user)
    end

    def edit
    end

    def create
      @reservation = Reservation.new(reservation_params) do |reservation|
        reservation.room_id = params[:room_id]
        reservation.user = current_user
      end

      if @reservation.save
        redirect_to(my_reservations_path, notice: t('.success'))
      else
        redirect_to(room_path(params[:room_id]), alert: t('.failed'))
      end
    end

    def update
      if @reservation.update(reservation_params)
        redirect_to(my_reservations_path, notice: t('.success'))
      else
        render(:edit, status: :unprocessable_entity)
      end
    end

    def destroy
      return if @reservation.user_id != current_user.id

      if @reservation.destroy
        redirect_to(my_reservations_path, notice: t('.success'))
      else
        redirect_to(my_reservations_path, alert: t('.failed'))
      end
    end

    private

    def set_reservation
      @reservation = Reservation.where(user: current_user).find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:check_in, :check_out)
    end

  end

end

app/controllers/users/rooms_controller.rb
module Users

  class RoomsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_room, except: %i[index new create]

    def index
      @rooms = Room.where(user: current_user)
    end

    def show
      @new_image = ActiveStorage::Attachment.new
    end

    def new
      @room = Room.new
    end

    def edit
    end

    def create
      @room = Room.new(room_params) { |room| room.user = current_user }

      if @room.save
        redirect_to(my_rooms_path, notice: t('.success'))
      else
        render(:new, status: :unprocessable_entity)
      end
    end

    def update
      if @room.update(room_params)
        redirect_to(my_room_path(@room), notice: t('.success'))
      else
        render(:edit, status: :unprocessable_entity)
      end
    end

    def destroy
      return if @room.user_id != current_user.id

      if @room.destroy
        redirect_to(my_rooms_path, notice: t('.success'))
      else
        redirect_to(my_room_path(@room), alert: t('.failed'))
      end
    end

    private

    def room_params
      params.require(:room).permit(
        :name, :location, :price_per_night, :start_date, :end_date, images: []
      )
    end

    def set_room
      @room = Room.where(user: current_user).find(params[:id])
    end

  end

end

app/views/users/rooms/_form.html.erb
<div class="container-sm">
  <%= form_with(model: room, url: url) do |form| %>
    <% if room.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(room.errors.count, 'error') %> prohibited this section from being saved:</h2>

        <ul>
          <% room.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <div class="mb-3">
        <%= form.label(:name, 'Name', class: 'form-label') %>
        <%= form.text_field(:name, class: 'form-control') %>
      </div>
      <div class="mb-3">
        <%= form.label(:location, 'Location', class: 'form-label') %>
        <%= form.text_field(:location, class: 'form-control') %>
      </div>
      <div class="mb-3">
        <%= form.label(:price_per_night, 'Price per night', class: 'form-label') %>
        <%= form.text_field(:price_per_night, class: 'form-control') %>
      </div>
      <div class="mb-3">
        <%= form.label(:start_date, 'Start date', class: 'form-label') %>
        <%= form.date_field(:start_date, class: 'form-control') %>
      </div>
      <div class="mb-3">
        <%= form.label(:end_date, 'End date', class: 'form-label') %>
        <%= form.date_field(:end_date, class: 'form-control') %>
      </div>
      <div class="mb-3">
        <%= form.label(:images, 'Images', class: 'form-label') %>
        <%= form.file_field(:images, accept: 'image/png,image/jpeg', multiple: true, class: 'form-control') %>
      </div>
      <%= form.submit('Save', class: 'btn btn-success') %>
    </div>
  <% end %>
</div>

app/views/users/rooms/edit.html.erb
<div class="container-fluid">
  <h1>Edit room</h1>

  <%= render('form', room: @room, url: my_room_path(@room)) %>
</div>

app/views/users/rooms/index.html.erb
<h1>My rooms</h1>
<%= link_to('Create new room', new_my_room_path, class: 'btn btn-success') %>

<%= render('shared/rooms', user_rooms: true) %>

app/views/users/rooms/new.html.erb
<div class="container-fluid">
  <h1>New room</h1>

  <%= render('form', room: @room, url: my_rooms_path) %>
</div>

app/views/users/rooms/show.html.erb
<div class="col-lg-8 mx-auto p-4 py-md-5">
  <div class="align-items-center pb-3 mb-3 border-bottom">
    <%= link_to('Edit room', edit_my_room_path(@room), class: 'btn btn-primary d-inline') %>
    <%= button_to('Delete room', my_room_path(@room), method: :delete, class: 'btn btn-danger', form: { class: 'd-inline '}) %>
    <div>
      <p class="fs-4"><%= @room.name %></p>
    </div>
    <div><span>Location: <%= @room.location %></span></div>
  </div>
  <div>
    <div class="row">
      <% @room.images.each do |image| %>
        <div class="col-md-4">
          <%= image_tag(image, class: 'card-image-top', width: '100%') %>
          <div class="card-body">
            <%= button_to('Delete image', my_room_image_path(@room, image), method: :delete, class: 'btn btn-danger') %>
          </div>
        </div>
      <% end %>
    </div>
    <hr class="col-3 col-md-2 mb-5">
    <p>Price per night: <%= @room.price_per_night %></p>
  </div>
</div>