config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  health_check_routes

  root "rooms#index"

  resources :rooms, only: %i[index show]
  namespace :my do
    resources :rooms, only: %i[index show edit new create update destroy] do
      member do
        delete :remove_image
      end
    end

    resources :reservations, only: %i[index create destroy]do
      member do
        put :confirmed
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord

  has_one_attached :image
  has_many_attached :gallery_images
  has_rich_text :description

  belongs_to :user
  has_many :reservations, dependent: :destroy

  validates :name, :location, presence: true
  validates :capacity, presence: true, numericality: { greater_than: 0 }
  validates :price_per_night_cents, presence: true, numericality: { greater_than: 0 }

  scope :not_reserved, lambda { |start_date, end_date|
                         where.not(id: Reservation.reserved(start_date, end_date).select(:room_id))
                       }
  scope :by_location, ->(location) { where(location:) }

  def reserved?(start_date, end_date)
    !id.in?(Reservation.reserved(start_date, end_date).pluck(:room_id))
  end

end

app/controllers/my/bookings_controller.rb
# frozen_string_literal: true

module My

  class BookingsController < ApplicationController

    before_action :authenticate_user!
    before_action :find_booking, only: %i[edit update destroy]

    def index
      @bookings = current_user.bookings
    end

    def edit
    end

    def update
      if @booking.update(booking_params)
        return redirect_to(my_bookings_path, flash: { success: t('messages.success') })
      end

      redirect_to(edit_my_booking_path(@booking), flash: { error: @booking.errors.full_messages })
    end

    def destroy
      @booking.destroy

      redirect_to(bookings_url, notice: @booking.errors.first || t('messages.success'))
    end

    private

    def find_booking
      @booking = current_user.bookings.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:from, :to)
    end

  end

end

app/controllers/my/reservations_controller.rb
class My::ReservationsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_reservation, only: %i[confirmed destroy]

  def index
    @status = params[:status]
    @status = Reservation::STATUS[:confirmed] unless Reservation::STATUS.values.include?(@status)

    @reservations = current_user.reservations

    @reservations = @reservations.unscoped.by_status(@status)
  end

  def create
    @reservation = current_user.reservations.new(reservation_params)
    @room = @reservation.room
    @reservations = Reservation.reserved_dates_room(@room.id)

    if @reservation.save
      redirect_to my_reservations_path, notice: I18n.t('messages.success')
    else
      render turbo_stream: turbo_stream.replace(
        'reservation_form',
        partial: 'my/reservations/form',
        locals:  { room: @room, reservation: @reservation, reservations: @reservations }
      )
    end
  end

  def confirmed
    @reservation.confirm!

    redirect_back(fallback_location: request.referer)
  end

  def destroy
    @reservation.cancel!

    redirect_back(fallback_location: request.referer)
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :room_id)
  end

end

app/controllers/my/rooms_controller.rb
class My::RoomsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @rooms = current_user.rooms
  end

  def show
    @reservations = @room.reservations
    render turbo_stream: turbo_stream.replace(
      'room_reservations',
      partial: 'my/rooms/reservations',
      locals:  { room: @room, reservations: @reservations }
    )
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = current_user.rooms.new(rooms_params)
    return render(:new, status: :unprocessable_entity) unless @room.save

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def update
    return render(:edit, status: :unprocessable_entity) unless @room.update(rooms_params)

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def destroy
    @room.destroy

    redirect_to my_rooms_path, notice: I18n.t('messages.success')
  end

  def remove_image
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge_later
    redirect_back(fallback_location: request.referer)
  end

  private

  def set_room
    @room = current_user.rooms.find(params[:id])
  end

  def rooms_params
    params.require(:room).permit(:name, :location, :capacity,
                                 :price_per_night_cents, :image, gallery_images: [])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all

    if params[:start_date].present? && params[:end_date].present?
      @rooms = Room.not_reserved(params[:start_date], params[:end_date])
    end
    @rooms = @rooms.by_location(params[:location]) if params[:location].present?

    @pagy, @rooms = pagy(@rooms)
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @reservations = Reservation.reserved_dates_room(@room.id)
  end

end

app/controllers/users/rooms_controller.rb
module Users

  class RoomsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_room, except: %i[index new create]

    def index
      @rooms = Room.where(user: current_user)
    end

    def show
      @new_image = ActiveStorage::Attachment.new
    end

    def new
      @room = Room.new
    end

    def edit
    end

    def create
      @room = Room.new(room_params) { |room| room.user = current_user }

      if @room.save
        redirect_to(my_rooms_path, notice: t('.success'))
      else
        render(:new, status: :unprocessable_entity)
      end
    end

    def update
      if @room.update(room_params)
        redirect_to(my_room_path(@room), notice: t('.success'))
      else
        render(:edit, status: :unprocessable_entity)
      end
    end

    def destroy
      return if @room.user_id != current_user.id

      if @room.destroy
        redirect_to(my_rooms_path, notice: t('.success'))
      else
        redirect_to(my_room_path(@room), alert: t('.failed'))
      end
    end

    private

    def room_params
      params.require(:room).permit(
        :name, :location, :price_per_night, :start_date, :end_date, images: []
      )
    end

    def set_room
      @room = Room.where(user: current_user).find(params[:id])
    end

  end

end

app/views/my/rooms/_form.html.erb
<%= form_with(model: [:my, room], local: true) do |form| %>
  <%= render partial: 'shared/error_messages', locals: { object: room } %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :capacity %>
    <%= form.number_field :capacity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price_per_night %>
    <%= form.number_field :price_per_night_cents, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.label :gallery_images, multiple: true %>
    <%= form.file_field :gallery_images, multiple: true, class: "form-control-file" %>
    <% if room.gallery_images.attached? %>
      <% room.gallery_images.each do |gallery_image| %>
        <%= form.hidden_field :gallery_images, multiple: true, value: gallery_image.signed_id %>
        <%= image_tag(gallery_image, height: '100') %>
        <%= link_to "Remove", remove_image_my_room_path(gallery_image), data: { turbo_method: :delete } %>
      <% end %>
    <% end %>
  </div>

  <div class="text-center">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/my/rooms/_reservations.html.erb
<div class="list-group">
  <% reservations.each do |reservation| %>
    <div class="d-flex justify-content-between">
      <div>
        <h5 class="mb-1">Start Date: <%= reservation.start_date %></h5>
        <p class="mb-1">End Date: <%= reservation.end_date %></p>
        <p class="mb-1">Status: <%= reservation.status %></p>
        <p class="mb-1">Total: <%= humanized_money_with_symbol(reservation.price_cents) %></p>
      </div>
      <div class="text-right">
        <% unless reservation.confirmed? %>
          <%= button_to confirmed_my_reservation_path(reservation), class: "btn btn-primary", method: :put do %>
            Confirm
          <% end %>
        <% end %>
        <%= button_to my_reservation_path(reservation), class: "btn btn-danger", method: :delete do %>
          Delete
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/my/rooms/edit.html.erb
<h1 class="display-4 text-center mb-5">Edit Room</h1>

<%= render 'form', room: @room %>

<div class="text-center mt-4">
  <%= link_to "Back", my_rooms_path, class: "btn btn-secondary" %>
</div>

app/views/my/rooms/index.html.erb
<div class="container">
  <h1 class="display-4 text-center mb-5">My Rooms</h1>

  <div class="text-center mb-3">
    <%= link_to "Create Room", new_my_room_path, class: "btn btn-primary" %>
  </div>

  <div class="list-group">
    <% @rooms.each do |room| %>
      <div class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <% if room.image.attached? %>
            <%= image_tag room.image.variant(resize: "100x100"), class: "img-thumbnail mr-3" %>
          <% end %>
          <% if room.gallery_images.attached? %>
            <% room.gallery_images.each do |image| %>
              <%= image_tag image.variant(resize: "100x100"), class: "img-thumbnail mr-3" %>
            <% end %>
          <% end %>
          <div>
            <h5 class="mb-1"><%= room.name %></h5>
            <p class="mb-1">Location: <%= room.location %></p>
            <p class="mb-1">Capacity: <%= room.capacity %></p>
            <p class="mb-1">Price per Night: <%= humanized_money_with_symbol(room.price_per_night_cents) %></p>
          </div>
          <div class="text-right">
            <%= link_to "Edit", edit_my_room_path(room), class: "btn btn-secondary mr-2" %>

            <% unless room.reservations.empty? %>
              <%= link_to "Show", my_room_path(room), data: { turbo_stream: false }, class: "btn btn-primary mr-2" %>
            <% end %>

            <%= button_to my_room_path(room), class: "btn btn-danger", method: :delete do %>
              Delete
            <% end %>
          </div>
        </div>
        <%= turbo_frame_tag "room_reservations", target: "_top" %>
      </div>
    <% end %>
  </div>
</div>

app/views/my/rooms/new.html.erb
<div class="container">
  <h1 class="display-4 text-center mb-5">Create New Room</h1>

  <%= render 'form', room: @room %>

  <div class="text-center mt-4">
    <%= link_to "Back", my_rooms_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/my/rooms/show.html.erb
<div class="container">
  <h1><%= @room.name %></h1>

  <p><strong>Address:</strong> <%= @room.address %></p>
  <p><strong>Images:</strong></p>
  <div class="row">
    <% @room.images.each do |image| %>
      <div class="col-md-4">
        <%= image_tag url_for(image), class: "img-thumbnail" %>
      </div>
    <% end %>
  </div>
  <p><strong>Rent per Night:</strong> <%= humanized_money_with_symbol(@room.price_per_night) %></p>

  <br>

  <%= link_to 'Edit', edit_my_room_path(@room), class: 'btn btn-secondary' %> |
  <%= link_to 'Destroy', my_room_path(@room), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm' %>
  <%= link_to 'Back', my_rooms_path, class: 'btn btn-primary' %>
</div>